num = int(input('Digite um número entre 0 a 9999: '))
n = str(num)
print('Analisando o número {}.'.format(n))
print('Unidade: {}'.format(n[0]))
print('Dezena: {}'.format(n[1]))
print('Centena: {}'.format(n[2]))
print('Milhar: {}'.format(n[3]))